# Generated by Django 3.1.6 on 2021-02-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('stock_name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=30)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('previous_closing_price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('percentage_change', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('year_high', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('year_low', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('price_change', models.DecimalField(decimal_places=2, max_digits=10000)),
            ],
        ),
    ]
