# Generated by Django 3.1.6 on 2021-02-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='market_cap',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='stock_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
