# Generated by Django 3.1.6 on 2021-02-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='close',
            field=models.TextField(default='26.76, 34.45, 45.43, 54.56'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='high',
            field=models.TextField(default='28.76, 38.45, 48.43, 58.56'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='index',
            field=models.TextField(default='2021-02-21, 2021-02-20, 2021-02-19, 2021-02-18'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='low',
            field=models.TextField(default='22.76, 32.45, 42.43, 52.56'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='open',
            field=models.TextField(default='28.76, 36.45, 44.43, 56.56'),
        ),
    ]
