# Generated by Django 3.1.6 on 2021-03-01 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capstone', '0004_auto_20210221_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='ownedBy',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
