# Generated by Django 3.1.6 on 2021-03-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_auto_20210227_0104'),
        ('capstone', '0005_ticker_ownedby'),
    ]

    operations = [
    ]
