# Generated by Django 3.1.6 on 2021-03-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_ownedpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedpackage',
            name='packageNum',
            field=models.IntegerField(default=-1),
        ),
    ]
