# Generated by Django 3.1.6 on 2021-03-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_ownedpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('info', models.JSONField(default='empty')),
            ],
        ),
    ]
