# Generated by Django 3.1.6 on 2021-03-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_stockjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockjson',
            name='info',
            field=models.JSONField(),
        ),
    ]
