# Generated by Django 3.1.6 on 2021-03-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_stockjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockjson',
            name='historic_monthly',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='stockjson',
            name='historic_yearly',
            field=models.JSONField(),
        ),
    ]
