# Generated by Django 3.1.6 on 2021-03-18 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0010_auto_20210317_1920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockJson',
        ),
    ]
