# Generated by Django 3.1.6 on 2021-03-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0010_auto_20210318_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockjson',
            name='historic_monthly',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='stockjson',
            name='historic_yearly',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='stockjson',
            name='info',
            field=models.JSONField(default={}),
        ),
    ]
