# Generated by Django 3.1.6 on 2021-03-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0011_auto_20210318_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockjson',
            name='historic_sales',
            field=models.JSONField(default={}),
        ),
    ]
