# Generated by Django 3.1.6 on 2021-03-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0012_stockjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockjson',
            name='historic_monthly',
            field=models.JSONField(default={'monthly': 'test'}),
        ),
        migrations.AddField(
            model_name='stockjson',
            name='historic_yearly',
            field=models.JSONField(default={'yearly': 'test'}),
        ),
    ]
