# Generated by Django 3.1.6 on 2021-03-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0013_auto_20210317_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockjson',
            name='historic_monthly',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='stockjson',
            name='historic_yearly',
            field=models.JSONField(default={}),
        ),
    ]
