# Generated by Django 3.1.6 on 2021-03-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0014_auto_20210317_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockjson',
            name='stock_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockjson',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
